-- CREATE --

--create table chart (id bigint generated by default as identity, total_price double, customer_id bigint, primary key (id));
--
--create table customer (id bigint generated by default as identity, phone varchar(255) not null, name varchar(255), primary key (id, phone));
--
--create table item (id bigint generated by default as identity, name varchar(255), price double, item_type varchar(255) not null, vendor varchar(255), chart_id bigint, primary key (id));

--create table chart_item (id bigint generated by default as identity, quantity integer, chart_id bigint, item_id bigint, primary key (id));

--create table purchase (id bigint generated by default as identity, purchase_date date, chart_id bigint, primary key (id));
--
--create table stock_item (id bigint generated by default as identity, quantity integer, item_id bigint, storage_id bigint, primary key (id));
--
--create table storage (id bigint generated by default as identity, name varchar(255), primary key (id));
--
--alter table chart add constraint fk_chart_customer foreign key (customer_id) references customer;
--
--alter table item add constraint fk_item_chart foreign key (chart_id) references chart;
--
--alter table chart_item add constraint fk_chart_item_chart foreign key (chart_id) references chart;

--alter table chart_item add constraint fk_chart_item_item foreign key (item_id) references item;

--alter table purchase add constraint fk_purchase_chart foreign key (chart_id) references chart;
--
--alter table stock_item add constraint fk_stock_item_item foreign key (item_id) references item;
--
--alter table stock_item add constraint fk_stock_item_storage foreign key (storage_id) references storage;

-- CUSTOMERS ----------------------------------------------------------------

insert into customer(name, phone) values('Pasquale', '+351987777777');
insert into customer(name, phone) values('Denver', '+351918564187');
insert into customer(name, phone) values('Paulo', '+351910988785');
insert into customer(name, phone) values('Tereza', '+351910654123');

-- STORAGES ----------------------------------------------------------------

insert into storage(name) values('MainStorage');

-- ITEMS --------------------------------

insert into item(name, price, item_type, vendor)
values('Potato', 5.0, 'VEGETABLE', 'Potatos Inc');
insert into item(name, price, item_type, vendor)
values('Corn', 1.0, 'VEGETABLE', 'Corn Farm');
insert into item(name, price, item_type, vendor)
values('Brocoli', 7.0, 'VEGETABLE', 'Brocco LTDA');
insert into item(name, price, item_type, vendor)
values('Tomato', 2.5, 'FRUIT', 'Green Fruits');
insert into item(name, price, item_type, vendor)
values('Pineapple', 11.75, 'FRUIT', 'Green Fruits');

-- STOCK ITEMS --------------------------------

insert into stock_item(item_id, quantity, storage_id)
values(1, 10, 1);
insert into stock_item(item_id, quantity, storage_id)
values(2, 100, 1);
insert into stock_item(item_id, quantity, storage_id)
values(3, 50, 1);
insert into stock_item(item_id, quantity, storage_id)
values(4, 2, 1);
insert into stock_item(item_id, quantity, storage_id)
values(5, 7, 1);

-- CHART --------------------------------

insert into chart(total_price, customer_id, customer_phone_id)
values(77.5, 2, '+351918564187');

insert into chart_item(quantity, chart_id, item_id) values(10, 1, 1);
insert into chart_item(quantity, chart_id, item_id) values(1, 1, 4);
insert into chart_item(quantity, chart_id, item_id) values(50, 1, 2);